### ISSUE TITLE
fi and fl ligatures

### ISSUE THREAD

**Issue by inferno986return** [erikdkennedy/figtree#19]
I was looking at an SVG that had a dynamic font and noticed that the "ffi" letters in "traffic" were rendered in a completely different font. 

Does Figtree support ligatures and if it doesn't, can it support the usual "fi" and "fl" letter groups?

**Comment by erikdkennedy** [comment]
Figtree doesn't have fi-ff-ffi-fl ligatures and I don't have any plans to add them.

(For context, many geometric sans serifs do away with these, and I don't see them as being of particular value. Worth noting that for Figtree, they'd be an especially big change, since the font name contains an "fi"!)
