### ISSUE TITLE
Backwards axis mappings?

### ISSUE THREAD

**Issue by erikdkennedy** [erikdkennedy/figtree#25]
Hey @emmamarichal, question for you. My intention was to have the bold weight be a bit lighter than (internal) 700. Here's the axis mappings as they stand:
<img width="841" alt="CleanShot 2023-03-09 at 14 37 44@2x" src="https://user-images.githubusercontent.com/3440839/224176342-36620cf5-defc-4342-bdde-907c124726a3.png">
To me, it appears like they're backwards. I _want_ to map 700 (external) to 660 (internal). But it looks like instead, I'm mapping 700 (internal) to 660 (external), giving me an even thicker bold than I desired. Is that indeed what's going on here? Thanks!

**Comment by emmamarichal** [comment]
Hi @erikdkennedy!

I'm not sure to understand very well the issue. The left column is what we call "user values", and it **has to** be 300/400/500/600/700/800/900.
And yes indeed, I pulled your last version, and the columns were backwards compared to your screenshot here. And I saw that the bold appeared bolder than before (it's probably due to the wrong order). I just reversed that I got the bold we had before.
 
So if you want a bold a bit lighter, you have to modify it directly in "exports" in font info, and put for example 640 (and then update the axis mapping with the good value).
The thing is, we can't really accept a weight change, because it will create regressions for people using it on web. 

So what I propose is that I export the font on my side, correct the axis mapping, do the QA and send you a new PR. Does it sound good for you?

Thanks :)
Emma

**Comment by erikdkennedy** [comment]
> The thing is, we can't really accept a weight change, because it will create regressions for people using it on web.

I'm pretty sure this axis mapping switch happened _after_ the last time I sent an update to GF. So in that case, wouldn't this _not_ cause a regression?

Also, is regression defined as "instance where glyph widths change, therefore causing text to reflow"?

> So what I propose is that I export the font on my side, correct the axis mapping, do the QA and send you a new PR. Does it sound good for you?

Sounds great! Thanks for all your help here, Emma! And sure enough, I botched it the first time I tried to merge your changes. But I think I got everything fixed now :)

**Comment by erikdkennedy** [comment]
> The left column is what we call "user values", and it has to be 300/400/500/600/700/800/900.

I think this may be backwards?

The Glyphs [tutorial on creating a variable font](https://glyphsapp.com/learn/creating-a-variable-font) shows the user values on the _right_.

![image](https://user-images.githubusercontent.com/3440839/230162451-2b640440-f712-4041-9641-4bb04552ee44.png)

And they say:

> The **left column** (or horizontal axis in the UI) represents the **internal coordinates**, make sure you match at least the instances you have set up. You can be more detailed though. The **right column** (or vertical axis in the UI) represents the **external coordinates**. Those should match the conventions described above.

I also can confirm that the 700 of the variable font _was_ too thick when viewed in a browser.

<img width="425" alt="CleanShot 2023-04-05 at 10 55 02@2x" src="https://user-images.githubusercontent.com/3440839/230163708-2cf2a53c-aa71-41ce-82a9-2d514b0a61af.png">

Given that, I've switched the axis mappings back to how they were before – and how I believe Glyphs intends for them to be.
